# Generated by Django 6.0.6 on 2026-07-14 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VeilleQuotidienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('resume', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('erreur', 'Erreur')], default='en_cours', max_length=20)),
                ('message_erreur', models.TextField(blank=True)),
                ('nombre_articles', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Veille quotidienne',
                'verbose_name_plural': 'Veilles quotidiennes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ArticleVeille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=200)),
                ('lien', models.URLField(max_length=2000)),
                ('date_publication', models.CharField(blank=True, max_length=100)),
                ('resume', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('veille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='accueil.veillequotidienne')),
            ],
            options={
                'verbose_name': 'Article de veille',
                'verbose_name_plural': 'Articles de veille',
                'ordering': ['ordre', '-score'],
            },
        ),
    ]
