# Generated by Django 6.0.6 on 2026-07-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veillequotidienne',
            name='articles_recuperes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='veillequotidienne',
            name='convergence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='veillequotidienne',
            name='doublons_supprimes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='veillequotidienne',
            name='duree_secondes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='veillequotidienne',
            name='sources_interrogees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
