# Generated by Django 6.0.6 on 2026-07-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_veillequotidienne_articles_recuperes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleveille',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='articleveille',
            name='importance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articleveille',
            name='mots_detectes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='articleveille',
            name='niveau_importance',
            field=models.CharField(blank=True, default='Veille documentaire', max_length=100),
        ),
        migrations.AddField(
            model_name='articleveille',
            name='niveau_preuve',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articleveille',
            name='one_health',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='articleveille',
            name='preuve',
            field=models.CharField(blank=True, default='Non déterminé', max_length=250),
        ),
        migrations.AddField(
            model_name='articleveille',
            name='raisons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
