from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("notice/", views.notice, name="notice"),
    path("outils/", views.outils, name="outils"),
    path("veille/", views.veille, name="veille"),
    path("veille/<int:veille_id>/", views.detail_veille, name="detail_veille"),
    path("veille/<int:veille_id>/pdf/", views.exporter_veille_pdf, name="exporter_veille_pdf"),
    path("redacteur/connexion/", views.redacteur_connexion, name="redacteur_connexion"),
    path("redacteur/deconnexion/", views.redacteur_deconnexion, name="redacteur_deconnexion"),
    path("redacteur/tableau-de-bord/", views.tableau_de_bord, name="tableau_de_bord"),
    path("redacteur/historique/", views.historique_veilles, name="historique_veilles"),
    path("redacteur/veille/<int:veille_id>/resume/", views.modifier_resume, name="modifier_resume"),
    path("redacteur/article/<int:article_id>/traduction/", views.modifier_traduction, name="modifier_traduction"),
    path("terrain/", views.terrain, name="terrain"),
    path("apropos/", views.apropos, name="apropos"),
    path("pompier/", views.pompier, name="pompier"),
    path("jeu/", views.jeu, name="jeu"),
    path("karate/", views.karate, name="karate"),
    path("bouger/questionnaire/", views.bouger_questionnaire, name="bouger_questionnaire"),
    path("bouger/resultat/", views.resultat_sport, name="bouger_resultat"),
    path("bouger/sport/<slug:sport_id>/", views.fiche_sport, name="fiche_sport"),
    path("miam/", views.miam, name="miam"),
    path("sedebrouiller/", views.sedebrouiller, name="sedebrouiller"),
    path("voyager-leger/", views.voyagerleger, name="voyagerleger"),
    path("bricoler/", views.bricoler, name="bricoler"),
    path("argent/", views.argent, name="argent"),
    path("travailler/", views.travailler, name="travailler"),
    path("check-up-rapide/", views.check_up_rapide, name="check_up_rapide"),
    path("suivi-personnalise/", views.suivi_personnalise, name="suivi_personnalise"),
    path("healthcompare/", views.healthcompare, name="healthcompare"),
]
