from .home import *
from .outils import *
from .terrain import *
from .apropos import *
from .notice import *
from .pompier import *
from .jeu import *
from .karate import *
from .sante import *
from .quotidien import *
from .pharmacie import *
from .tetris import *
from .space import *
from .contact import *
from .combat import *